In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df1=pd.read_csv(r'F:\Google classroom\KNN\Social_Network_Ads.csv')
df1.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
X=df1.iloc[:,2:4]
y=df1.Purchased
X,y

(     Age  EstimatedSalary
 0     19            19000
 1     35            20000
 2     26            43000
 3     27            57000
 4     19            76000
 ..   ...              ...
 395   46            41000
 396   51            23000
 397   50            20000
 398   36            33000
 399   49            36000
 
 [400 rows x 2 columns],
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 395    1
 396    1
 397    1
 398    0
 399    1
 Name: Purchased, Length: 400, dtype: int64)

In [4]:
df1.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
from sklearn.preprocessing import StandardScaler
ss1=StandardScaler()
X=ss1.fit_transform(X)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_pred1=reg.predict(X_test)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [9]:
acc_score_LR=reg.score(X_test,y_test)
acc_score_LR

0.89

In [10]:
#K-NN
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier()
knn1.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
y_pred2=knn1.predict(X_test)
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [12]:
acc_score_KNN=knn1.score(X_test,y_test)
acc_score_KNN

0.93

# Importing dataset on which we will perform the future prediction


In [13]:
df2=pd.read_excel(r'F:\Google classroom\KNN\future prediction.xlsx')
df2.head()

User ID  Gender  Age  EstimatedSalary
0  1674381    Male   29            39000
1  1674382  Female   14            34500
2  1674383    Male   28            40000
3  1674384  Female   58            56490
4  1674385  Female   80            59000

In [14]:
x2=df2.iloc[:,2:]
x2

Age  EstimatedSalary
0    29            39000
1    14            34500
2    28            40000
3    58            56490
4    80            59000
5    90            41000
6   100            23000
7    45            20000
8    37            33000
9    48            23000
10   59            64000
11   60            33000
12   61            23000
13   62            45000

In [15]:
from sklearn.preprocessing import StandardScaler
ss2=StandardScaler()
x2=ss2.fit_transform(x2)

In [16]:
#future pred. by LR
future_predLR=reg.predict(x2)
future_predLR

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [17]:
#future pred. by KNN
future_predKNN=knn1.predict(x2)
future_predKNN

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)